from __future__ import annotations

PIC_BY_MODULE = {
    "OMA": "Nguyen Van A",
    "SKMSAgent": "Do Thi B",
    "SEM": "Tran Van C",
    "SKPM": "Le Van D",
}

FIELD_WEIGHTS = {
    "search_text": 1.2,
    "evidence_text": 1.5,
    "raw_comments": 0.8,
}

LEVEL_WEIGHTS = {
    "strong": 10,
    "medium": 4,
    "weak": 1,
}

MODULE_KEYWORDS = {
    "OMA": {
        "strong": [
            "vtshalsecureelementv1_0targettest",
            "vtshalsecureelementtargettest",
            "secureelementhidltest",
            "ctsomapitestcases",
            "omapi cts",
            "omapi cts applet",
            "com.android.se",
            "android.se.omapi",
            "secureelement-accesscontrolenforcerno"
        ],
        "medium": [
            "vts",
            "cts",
            "setupchannelaccess",
            "secureelementservice",
        ],
        "weak": [
            "no_such_element_error",
            "omapi",
            "secureelementservice",
            "apdu",
            "assertionerror:",
            "[s5e5535]",
            "securityexception:",
            "setupchannelaccess",
            "accesscontrolexception:",
            "secureelement-accesscontrolenforcerno",
            "nfcservice",
            "native:",
            "buildid:",
            "lee/smartphone",
            "kernel",
            "binderproxy",
            "nfcservice$nfcservicehandler",
            "service:",
            "/sri-bangalore:2024",
            "core"
        ],
    },
    "SKMSAgent": {
        "strong": [
            "skmsagent",
            "com.skms.android.agent",
            "samsungseagent",
            "tsmagent",
            "kms",
            "skms",
            "skms agent",
            "requested",
            "cplc registration",
            "[authfw][fclnt]registration"
            "secapploader",
        ],
        "medium": [
            "com.samsung.android.ese",
            "donghoon",
            "permission",

        ],
        "weak": [
            "package info",
            "not compatible at all countries",
            "google team",
            "thales_hal",
            "[ut9",
            "cifrequest",
            "[esecontroller]",
            "selectable",
            "domain:personalized",
            "@long,\r\nplease",
            "nga/security",
            "aid",
            "connectivitymanager",
            "digital_key_ta_entry:",
            "servicemanager:",
            "samsungpay",
            "blockchain",
            "iccc",
            "lee/wallet"
        ],
    },
    "SEM": {
        "strong": [
            "sem daemon",
            "sem_daemon",
            "semfactoryapp",
            "ro.security.esest",
            "ese restricted mode",
            "sec_ese_cospatch",
            "esecos_daemon",
        ],
        "medium": [
            "thales_hal",
            "gemalto_p3",
            "cospatch",
            "ese_property",
            "concurrent",
            "lsi",
            "ese1",
            "secesespi_open",
            "_openspidrv",
            "initialized",
        ],
        "weak": [
            "startspitimer",
            "sw : 6a82",
            "jcop",
            "secureelementservice",
            "init:",
            "wearable",
            "spi:",
            "[s5e8845]\r\n\r\n\r\n",
            "revision]:",
            "watch",
            "patch",
            "cnt",
            "[ro.boot.revision]",
            "[ro.build.version.release]",
        ],
    },
    "SKPM": {
        "strong": [
            " e skpm",
            "skpm",
            "skpm:",
            "skpm_hidl_client",
            "skpm_keyinjection",
            "skpm_injectedkeyverification",
            "skpmoperation",
            "vendor.samsung.hardware.security.skpm",
            "key verify error",
            "provisioning fail",
        ],
        "medium": [
            "there is no key file",
            "mbedtls_net_connect",
            "failed, ret : -41",
            "failed, ret : -20",
            "server / port failed",
            "inj error",
            "fido key injection",
            "injectedkeyverification",
            "uaf_asm_status_error",
            "authfw",
            "fido",
            "cellular",
            "skpm_injectedkeyverification",
        ],
        "weak": [
            "samsungaccount:",
            "speed:",
            "[pss2n6007]\r\n",
            "requested",
            "mlo",
            "[authfw][cmn]skpmoperation:",
            "called,",
            "transports:",
            "[pass][pass]postuafserviceoperation:",
            "inj",
            "samsungpass",
            "window",
            "underlyingnetworks:",
            "null]",
            "netdeventlistenerservice:",
            "authfw",
            "[pass][pass]register:",
            "provider",
            "adminuids:",
            "installed=true",
            "suspended=false",
            "rssi:",
            "transportinfo:",
            "bssid:",
            "returned",
            "allow_clear_user_data",
            "distractionflags=0",
            "frequency:",
            "passkey",
            "minextensionversions=[]\r\n",
        ],
    },
}

# Một vài rule ưu tiên để resolve overlap
PRIORITY_RULES = [
    {
        "name": "SKPM_direct_log",
        "module": "SKPM",
        "any_keywords": [
            "skpm_keyinjection",
            "skpm_injectedkeyverification",
            "skpm_hidl_client",
            " e skpm",
            "skpm",
        ],
        "bonus": 20,
    },
    {
        "name": "OMA_vts_omapi",
        "module": "OMA",
        "any_keywords": [
            "vtshalsecureelementv1_0targettest",
            "vtshalsecureelementtargettest",
            "ctsomapitestcases",
            "OMAPI CTS applet",
        ],
        "bonus": 18,
    },
    {
        "name": "SKMSAgent_package_or_app",
        "module": "SKMSAgent",
        "any_keywords": [
            "skmsagent",
            "com.skms.android.agent",
            "kms agent",
            "skms agent",
        ],
        "bonus": 16,
    },
]

UNKNOWN_THRESHOLD = 1.0
LOW_CONFIDENCE_GAP = 4.0
HIGH_CONFIDENCE_GAP = 10.0